### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by SKDevGit** [matomo-org/plugin-MarketingCampaignsReporting#109]
MarketingCampaignsReporting plugin when activated is generating HTTP 500 error during tracking. If the plugin is disabled the error goes away. We are on Matomo 4.2.1. Please help.

**Comment by AltamashShaikh** [comment]
@SKDevGit Can you see the error in `tmp/logs/matomo.log` ?
If yes can you share that here it will help us to know what is breaking exactly for you.

**Comment by SKDevGit** [comment]
Thanks for your response. No, there are no errors recorded in the
matomo.log file.

**Comment by AltamashShaikh** [comment]
@SKDevGit Can you try enabling `debug_mode` ? Refer this [FAQ](https://matomo.org/faq/how-to/faq_20991/) on how to enable it and check if you can see anything in the `matomo.log` file

**Comment by SKDevGit** [comment]
There are no errors even after enabling the debug mode.

**Comment by AltamashShaikh** [comment]
@SKDevGit Does it log anything in your webserver's error.log
For example if you are using Apache as a webserver you can check apache's error log file

**Comment by SKDevGit** [comment]
We use nginx. Logs are updated in matomo.log and access.log but there are no errors in matamo.log and nginx error.log files.

**Comment by SKDevGit** [comment]
Please find attached the log file. 
[matomo.log](https://github.com/matomo-org/plugin-MarketingCampaignsReporting/files/9605820/matomo.log)

**Comment by AltamashShaikh** [comment]
@SKDevGit I cannot see any 500 error in the above log, looks okay

**Comment by SKDevGit** [comment]
Yes, there is no 500 error in the log. The error is coming in the browser
if marketingcampaignsreporting plugin is activated.

**Comment by AltamashShaikh** [comment]
@SKDevGit please share the failing url from network tab

**Comment by SKDevGit** [comment]
This is the url. If it works the first time, please try again. It will fail
from the second time onwards. The error will go away if the plugin is
disabled. Thanks

https://beacon.crigloo.com/matomo.php?action_name=Crigloo%20%3A%3A%20Home&idsite=127&rec=1&r=961979&h=18&m=36&s=21&url=https%3A%2F%2Fwww.crigloo.com%2F&_id=62871f1c7a4bb544&_idn=0&_refts=1663679172&_ref=https%3A%2F%2Fwww.google.com%2F&send_image=0&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=1440x900&pv_id=m3y1Pq&pf_net=0&pf_srv=7.90000057220459&pf_tfr=1.0999994277954102

**Comment by AltamashShaikh** [comment]
@SKDevGit for me it always results with status `204`, tried with both browser and cli
![Screenshot from 2022-09-21 08-07-49](https://user-images.githubusercontent.com/14902277/191401885-0a7d7bae-7d04-44a4-a39f-bc9462f6975b.png)

**Comment by SKDevGit** [comment]
I had the plugin turned off to prevent the error. The plugin is activated
now. Please try again, the 500 error will appear.

Thanks,

**Comment by AltamashShaikh** [comment]
@SKDevGit I tried updating my local instance to Matomo 4.2.1 version and use the URL you provided in my local instance and it works as expected.
All requests are 204, I would request you to enable error_reporting and check for error message or its better you upgrade your Matomo instance to latest version.
Without any error log or stack trace it will be very difficult to find the cause of bug.

**Comment by SKDevGit** [comment]
Thanks.

1) Is there any other way of enabling error reporting? I have set the log
level to ERROR but still no error shows up.
2) Yes, upgrading is an option but we cannot do it right away. Our db and
transaction volumes are high. When we tried upgrading in the test instance
the process did not complete successfully. So I am a bit hesitant about an
upgrade now.
Btw, we use docker-compose for launching matomo. If there is a way to
resolve the issue without upgrading, that will be ideal for us. You have
been very helpful and I really appreciate it.

**Comment by AltamashShaikh** [comment]
hey @SKDevGit Is it a Wordpress installation ?
If yes check this - https://stackoverflow.com/questions/55462067/docker-compose-file-not-showing-php-errors-from-wp-config-php
Or check if this is set `ini_set('error_log', '/dev/stdout');` and due to which nothing was being logged in the file

**Comment by SKDevGit** [comment]
We got the error resolved by upgrading matomo. Perhaps it was due to an
incompatibility issue between Matomo and the plugin versions. I wish the
documentation were clear.

**Comment by SKDevGit** [comment]
I enabled the DEBUG mode. But there are no errors reported in the
matomo.log file. Thanks
