### ISSUE TITLE
Please make utm_placement resolution available to Matomo

### ISSUE THREAD

**Issue by uncleabe** [matomo-org/plugin-MarketingCampaignsReporting#130]
Hello all,

we like to use the plugin very much and we are very satisfied with the result. Besides the common utm parameters like utm_campaign or utm_medium, other parameters not mentioned in the description are resolved and passed to Matomo: e.g. utm_group.

see: https://plugins.matomo.org/MarketingCampaignsReporting

Unfortunately, utm_placement did not pass any data. Only when we changed it to mtm-prefix, data ran up in Matomo.

Now we would like to use utm_placement instead of mtm_placement, so that we not only have tracking via Matomo, but also via Hubspot.

Could you make this possible and integrate it?

Thanks a lot in advance.
Andreas

**Comment by AltamashShaikh** [comment]
@uncleabe Check the “Customising your campaign parameters” section [here](https://plugins.matomo.org/MarketingCampaignsReporting) and try overriding the campaign_placement under MarketingCampaignsReporting in your config.ini.php

**Comment by AltamashShaikh** [comment]
@uncleabe can we close this issue ?

**Comment by uncleabe** [comment]
Hi @AltamashShaikh,

Thanks a lot for your help. I've made the changes to the config.ini.php and just checked the parameters in Matomo. **It worked.**
