### ISSUE TITLE
No connection between campaing reports before and after update

### ISSUE THREAD

**Issue by scharj** [matomo-org/plugin-MarketingCampaignsReporting#142]
I yesterday (01/10/24) updated the Marekting Campaings Reporting to Version 5.0.2
Since then I am not able to form a sum with dates before 01/10/24.

If I want to form a sum from 01/01/24 to 01/11/24 the plugin only shows the sum from 01/10/24 to 01/11/24.

I found out, that the only way to form a sum from 01/01/24 to 01/11/24 is to form two sums, the first from 01/01/24 to 01/09/24, the second from 01/10/24 to 01/11/24 and form the sum by hand, which seems to be a bug to me, isn't it?

**Comment by sgiehl** [comment]
Hi @scharj,
Sorry to hear you are having trouble with the plugin.
Which version did you update from?
And how exactly are you trying to "form a sum". Are you selecting a date range in the period selector? Does it show correct number for e.g. weeks or the whole month?

**Comment by scharj** [comment]
Hi @sgiehl 

I have tried all options, it does not work for date range, month or week, as soon as the date, where the plugin was updated is involved within the range.

i.e.:

- December would work, January does not, as 01/10/24 was in the middle of January
- The first week of January would work, the second not, as 01/10/2024 was a Wednesday.

**Comment by scharj** [comment]
and sorry, @sgiehl I do not know the version I updated from ...

**Comment by AltamashShaikh** [comment]
@scharj Did you try invalidating and re-archiving the data ? You can follow this [guide](https://matomo.org/faq/how-to/faq_155/) to invalidate and archive the data

**Comment by Stan-vw** [comment]
@scharj I'll close this ticket as we haven't heard back from you, and no other people have reported this problem.
Feel free to reopen in case it's still an issue after following this [guide](https://matomo.org/faq/how-to/faq_155/) to invalidate and archive the data
