### ISSUE TITLE
[Bug] Reporting issue, if multi dimensional report is shown "flat"

### ISSUE THREAD

**Issue by peterbo** [matomo-org/plugin-MarketingCampaignsReporting#144]
Reproducible on the Demo:

- https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=year&date=2023-01-10&idSite=1&category=Referrers_Referrers&subcategory=Referrers_Campaigns
- Make sure to select the whole year 2023 or any other range that includes Keyword subdata-tables under the campaign names
- Select "Make it flat" for the Campaign Names widget
- Navigate to the next page of the report 
- -> An error is displayed "There is no data for this report. ". Also, it is not possible to search for any campaign name, that has a subdata-table attached

**Comment by snake14** [comment]
Hi @peterbo . Thank you for taking the time to create this issue and bringing the paging problem to our attention. I was able to reproduce the paging issue on demo and our staging environment as well. I am marking this bug to be prioritised by our Product team.

**Comment by AltamashShaikh** [comment]
@peterbo Should be fixed with a new release.
