### ISSUE TITLE
Can't get campaign data

### ISSUE THREAD

**Issue by pablitok** [matomo-org/plugin-MarketingCampaignsReporting#19]
Hello. By mistake I've disabled the plugin for a month, yesterday I've enabled it again but I'm not being able to get the campaign data.  I'm using Matomo **3.0.4** and I've tried plugin version **1.3.1** (AdvancedCampaignReporting) and **3.0.2** (MarketingCampaignsReporting)
To reprocess data I'm using the instructions on https://matomo.org/faq/how-to/faq_59/:
`./console core:invalidate-report-data --dates=2018-05-1,2018-06-01`
`./console core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000`
But when I check the `campaing_{name,source,id,etc}` fields on the `visit_log` table, they are empty for the reprocessed data

**Comment by mattab** [comment]
The only way to have the campaign data is to replay the tracking logs: https://piwik.org/faq/log-analytics-tool/faq_19221/
after first deleting all the data that you will replay (to avoid double counting)

This should work
