### ISSUE TITLE
Move the dimensions to the "Acquisition" category rather than "Visitors" category

### ISSUE THREAD

**Issue by mattab** [matomo-org/plugin-MarketingCampaignsReporting#23]
Currently we have the dimensions under the Visitors category:

![Screenshot from 2019-06-07 15-53-39](https://user-images.githubusercontent.com/466765/59080366-70802480-893c-11e9-9be6-064cadf450bf.png)

We'd prefer to have them under the Acquisition category next to the other acqusition dimensions:

![Screenshot from 2019-06-07 15-54-05](https://user-images.githubusercontent.com/466765/59080373-7e35aa00-893c-11e9-8bd7-593d73348ffb.png)

This will be consistent and make it easier to create Custom Segments, and Custom Reports.

**Comment by sgiehl** [comment]
The campaign dimensions meanwhile have their own category:

![image](https://user-images.githubusercontent.com/1579355/85665516-c5174e80-b6bb-11ea-8b73-e8308e02f824.png)

@mattab is that ok, or shall we move to `Acquisition`?

**Comment by sgiehl** [comment]
ping @mattab @tsteur

**Comment by tsteur** [comment]
@sgiehl I reckon it's fine. Is it maybe easy to move the campaigns category after "acuqisition"? Otherwise might be better to have it in `Acquisition` and then their name be `Campaign Medium` instead of just `Medium`

**Comment by mattab** [comment]
Sounds good to me to also move the Campaigns one under Acquisiton as well as these :+1: and remove he Campaigns section.
