### ISSUE TITLE
Additional modern campaign tracking parameters

### ISSUE THREAD

**Issue by ryan-boder** [matomo-org/plugin-MarketingCampaignsReporting#25]
I'm in the process of transitioning from Google Analytics to Matomo. Tracking advertising campaigns is not as powerful in Matomo because the campaign tracking parameters (pk_*) are limited to equivalents of the old utm parameters that Urchin defined decades ago. These parameters are useful but they don't cover all the dimensions needed to track an advertising campaign today.

The big ad platforms no longer rely on utm parameters for their analytics. Instead, they have their own proprietary "click id" parameters (gclid, fbclid, mscklid) [that allow a lot more useful information to be tracked in a single query string parameter](https://support.google.com/analytics/answer/1733663?hl=en). This puts Matomo at a big disadvantage because it doesn't have important dimensions such as target audience and ad placement/positioning. These details are available via URL templates so the only thing preventing Matomo from getting them is Matomo's own limitation.

Currently I'm passing them through by combining multiple fields from the ad platforms into Matomo pk parameters. For example, I'm putting both the Ad Group and the search keywords in pk_keywords and I'm putting the Ad ID and the Ad placement in pk_content. This doesn't work very well because they're independent dimensions but are being forced together so analysis and reporting on them is less powerful.

I propose that Matomo add additional pk_ parameters to track important dimensions that a marketer today can't really be effective without. For example, you might add

- pk_group or pk_audience for the target audience
- pk_placement or pk_position for where the ad showed up to the visitor
- pk_etc for additional (maybe platform specific) data that is useful but isn't common enough across platforms to justify a standard parameter

In my opinion, if Matomo wants to complete in today's market it needs to innovate and not just follow a defactor standard from 20 years ago. As the leading open 3rd party analytics platform you have the opportunity to set the new standard.

An alternative solution might be making it easy for users to define their own campaign parameters but I'd prefer to see Matomo define the more common ones as standard.

**Comment by tsteur** [comment]
Cheers @ryan-boder 

@sgiehl that could be something for Matomo 4?

**Comment by sgiehl** [comment]
@tsteur we can also add this new columns to this plugin before Matomo 4. Maybe we can implement it in a way, where the user needs to activate the new columns if the plugin was already installed before, so no one is forced to do an update on the log tables.

But which columns shall we add?

@ryan-boder I'm not that deep into the autotagging feature. Which query params is Google (or other ad providers) able to automatically add to the target URL? Or would you need them to pass custom values?

**Comment by tsteur** [comment]
It's not really a priority before Matomo 4 and it's better to wait until Matomo 4 with the big log table updates just to have ideally the updates at once. It's quite painful to update otherwise and maybe unexpected.

**Comment by tsteur** [comment]
Also I don't think too many users would enable it manually using a command etc

**Comment by ryan-boder** [comment]
@sgiehl I've only used Google, Facebook and Microsoft but here are the auto parameters that can be passed in a URL template.

- [Google](https://support.google.com/google-ads/answer/6305348) (scroll to Available ValueTrack parameters -> Final URL, tracking template or custom parameter or see [here](https://www.karooya.com/blog/list-of-all-valuetrack-parameters-in-google-adwords/) for a shorter but not as complete list)
- [Facebook](https://www.facebook.com/business/help/1016122818401732) (scroll to URL Dynamic Parameters)
- [Microsoft](https://help.ads.microsoft.com/#apex/3/en/56799/0) (scroll to Destination URL, final URLs, tracking templates and custom parameters)

Currently I'm including the network/site source in the pk_source and, the ad group/set in pk_keyword and the placement/position in pk_content. I can't say that's the best way to do it or that those are the only important parameters but they are important and are common across those 3 ad platforms. I'm appending them to the normal data that goes in those parameters so they don't show as independent dimensions in reports & summaries.

**Comment by mattab** [comment]
@tsteur maybe this is worth doing in matomo 4?

**Comment by tsteur** [comment]
No preference @mattab I'm not so much into this topic and not sure how much work it would be

**Comment by tsteur** [comment]
@mattab @sgiehl if we want to implement this, we need to implement it in the next 3 days (this week) as I understand this would trigger a big schema change.

**Comment by sgiehl** [comment]
Implementing some dimensions for campaigns won't be that much work, but we actually only need a decision which dimensions we actually want to offer. Alternatively we could also maybe add 5 "nameless" dimensions (e.g. campaign_dimension_1 to _5) and make them configurable like the custom dimensions

**Comment by tsteur** [comment]
Making them configurable sounds maybe like a lot of work when in that case also simply custom dimensions could be used.

Could we for now add two dimensions for 

```
pk_group for the target audience
pk_placement  for where the ad showed up to the visitor
```

@ryan-boder `pk_etc for additional (maybe platform specific) data that is useful but isn't common enough across platforms to justify a standard parameter` not so sure about this one and it might cause a bit of confusion to the user. I suggest in this case it might be possible to use a custom dimension instead if really needed?

**Comment by sgiehl** [comment]
I'll create a PR to add two new dimensions `Group` and `Placement` for now.
