### ISSUE TITLE
Campaign ID not avail in API, not appearing in Archiver

### ISSUE THREAD

**Issue by jpark313** [matomo-org/plugin-MarketingCampaignsReporting#40]
I am using the pk_cid parameter to capture campaign IDs.  However, these IDs are not present on the dashboard, and digging into Archiver.php, it does not appear w/ the listed constants, nor is there a public function in API to retrieve these values.

**Comment by sgiehl** [comment]
Hi @jpark313. Thanks for creating the issue. Just checked the code. At the moment it seems only possible to use the campaignid for segmentation (e.g. `campaignId=myID`). But it would indeed make sense to also build reports for the campaign ids.
