### ISSUE TITLE
WordPress suggests update to 4.0.1 which breaks current version of Matomo in WP Repo

### ISSUE THREAD

**Issue by danieljwonder** [matomo-org/plugin-MarketingCampaignsReporting#51]
I presume this is a simple version incompatibility for Matomo version 3 vs 4? WordPress is suggesting that I update to version 4.0.1. Once updated the following errors are thrown:

```
Fatal error: Uncaught Error: Call to undefined function DI\autowire() in ~/matomo/app/public/wp-content/plugins/MarketingCampaignsReporting/config/config.php on line 8
( ! ) Error: Call to undefined function DI\autowire() in ~/matomo/app/public/wp-content/plugins/MarketingCampaignsReporting/config/config.php on line 8
```

**Comment by tsteur** [comment]
Hi @danielmcclure 

the Matomo for WordPress Marketplace plugin was falsely sending you an update of the plugin that is only compatible with the next major version of Matomo (Matomo 4 vs currently Matomo 3 is used). 

To solve this problem there are two ways:

* Delete the plugin and install it again
* Or download the correct version from https://plugins.matomo.org/api/2.0/plugins/MarketingCampaignsReporting/download/3.1.1 and replace it manually in the `wp-content/plugins` directory.

Let me know if you need help with any of this.

**Comment by tsteur** [comment]
We have also released an update for `Matomo Marketplace for WordPress` plugin to prevent this issue in the future.
