### ISSUE TITLE
How to track using HTTP API

### ISSUE THREAD

**Issue by JE4GLE** [matomo-org/plugin-MarketingCampaignsReporting#53]
Hello,

what are the parameter names for the [HTTP Tracking API](https://developer.matomo.org/api-reference/tracking-api)?
I want to send campaign info using the tracking API.

Thanks!

**Comment by tsteur** [comment]
Hi @JE4GLE AFAIK there aren't any specific tracking parameters that you can use and you would instead have the campaign parameters in the URL that you are tracking see eg https://matomo.org/docs/tracking-campaigns/

**Comment by JE4GLE** [comment]
So if I have just the campaign parameters, I have to create a URL and send it within the `url` parameter?

**Comment by tsteur** [comment]
Exactly 👍
