### ISSUE TITLE
Campaign name does not exist in custom report dimension list

### ISSUE THREAD

**Issue by kompa3** [matomo-org/plugin-MarketingCampaignsReporting#68]
Matomo version: 3.14.1.
MarketingCampaignsReporting version: v3.1.1.

Campaign Name and other properties should be selectable in Custom Reports dimension list, under Acquisition category (or previously Campaigns category, see https://github.com/matomo-org/plugin-MarketingCampaignsReporting/issues/23).

However, I have the plugin in use and there are campaigns but no such things can be selected in Custom Reports dimensions:

![image](https://user-images.githubusercontent.com/9412499/124451561-31786380-dd8e-11eb-8d27-cc696ae0e56e.png)

**Comment by sgiehl** [comment]
Hi @kompa3 
Thanks for creating the issue. We highly recommend updating to Matomo 4. 
I have just checked that, and in Matomo 4 using the latest versions of CustomReports and MarketingCampaignsReporting plugin the campaign dimensions are correctly available. So this seems to be fixed meanwhile.
