### ISSUE TITLE
Wrong Links in documentation

### ISSUE THREAD

**Issue by criwe** [matomo-org/plugin-MarketingCampaignsReporting#71]
Hi,
the link to the "user guide " on https://plugins.matomo.org/MarketingCampaignsReporting#documentation points to https://piwik.org/docs/tracking-campaigns/ (404 error). I think https://matomo.org/docs/tracking-campaigns/ would be right.

Same for the "URL Builder" link.

Best,
Christoph

**Comment by Findus23** [comment]
Hi,

The piwik.org link properly redirects for me:
```text
➜  ~ curl -i https://piwik.org/docs/tracking-campaigns/ 
HTTP/1.1 301 Moved Permanently
Date: Mon, 16 Aug 2021 10:27:01 GMT
Server: Apache
Location: https://matomo.org/docs/tracking-campaigns/
Content-Length: 251
Content-Type: text/html; charset=iso-8859-1
Via: 1.1 alproxy

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://matomo.org/docs/tracking-campaigns/">here</a>.</p>
</body></html>
```
Nevertheless old piwik.org links could be replaced
